# Generated by Django 6.0 on 2025-12-12 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('key', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('seokey', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('icon_url', models.URLField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('key', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='webcams.category')),
            ],
        ),
        migrations.CreateModel(
            name='Webcam',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('last_update', models.DateTimeField()),
                ('heading', models.PositiveIntegerField(blank=True, null=True)),
                ('refresh_delay', models.PositiveIntegerField()),
                ('map_radius', models.PositiveIntegerField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('image_width', models.PositiveIntegerField()),
                ('image_height', models.PositiveIntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webcams', to='webcams.group')),
            ],
        ),
    ]
