# Generated by Django 6.0 on 2025-12-13 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CongestionEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('score', models.PositiveIntegerField()),
                ('webcam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='congestion_est', to='webcams.webcam')),
            ],
        ),
    ]
