# Generated by Django 6.0 on 2025-12-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcams', '0002_congestionestimate'),
    ]

    operations = [
        migrations.AddField(
            model_name='congestionestimate',
            name='num_vehicles',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
